services:
  - type: web
    name: vibechess
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
