services:
  - type: web
    name: vibechess
    env: python
    buildCommand: |
      apt-get update && apt-get install -y stockfish
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
